import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MyThemeProvider } from "@/components/providers/ThemeProvider";
import { ThemeToggle } from "@/components/shared/ThemeToggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HandCrafted",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth transition-all">
      <body className={inter.className}>
        <MyThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex min-h-screen flex-col">
            <ThemeToggle />
            {children}
          </div>
        </MyThemeProvider>
      </body>
    </html>
  );
}
